### PR TITLE
chore: update the views counter to approx views from June.

### PR DESCRIPTION
**Pull request by Mohammed-Salman-Shaikh**
Change to current month.
And updated views of top 8 channels

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
We'll need it done for all the channels not only top 8.

**Comment by Mohammed-Salman-Shaikh** [comment]
Done all changes needed

**Review by KendallDoesCoding — COMMENTED** [review]
Looks good but just a question. Where did you source this information from?

**Comment by Mohammed-Salman-Shaikh** [comment]
*"About page"* of every YouTube channel. 
I manually visited every page to collect this info.

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@Mohammed-Salman-Shaikh - thanks for your contribution!

**Comment by Mohammed-Salman-Shaikh** [comment]
@KendallDoesCoding Welcome

**Pull request merged**
