### PR TITLE
Add table content to README.md

### PR DESCRIPTION
**Pull request by Isfaqul**

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@Isfaqul - you deleted the README.md?

**Comment by Isfaqul** [comment]
I think I am not entirely sure about github. I probably need to learn about git first and then try again. I am sorry, if I created problems.

**Comment by KendallDoesCoding** [comment]
> I think I am not entirely sure about github. I probably need to learn about git first and then try again. I am sorry, if I created problems. @KendallDoesCoding

No worries. Ik your new to open-source. You will learn.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding I have a python script to do the job for us. But we will have to use github action to run this script every time there is a change in the html file. The script is based on BS4

Sure. Can you make another PR and what the setup has to be done on the gh-action?

**Comment by Isfaqul** [comment]
I think you will know better about the GH actions. So basically, we will need to install dependecies, which is BS4 and run the script, everytime there is a commit to the index.html file.

**Comment by Isfaqul** [comment]
@KendallDoesCoding Hi, just made a PR.

**Pull request merged**
