### PR TITLE
[Enhancement ✨]-Restyled the Homepage and Add/Remove-Youtuber pages

### PR DESCRIPTION
**Pull request by ayushichoudhary-19**
Added better font, hover effects and colors to the page. Also separated the various elements from the container to make it look better.

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@MayankBansal12 - pls review.

**Review by MayankBansal12 — CHANGES_REQUESTED** [review]
- The home page looks good. However, a couple of changes are required. There is an add youtuber button now so you will have to take care of that. Also the YouTuber count, you can move to the navbar at the right. 


- In the /addyoutuber, the form looks a bit odd. Can you make it even by aligning the items to the center and also fixing the width of the button?
add-youtuber

- After making the changes, try to add the screenshots in the description so that it becomes easy to review.

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Hi,

Please make the above changes listed by @MayankBansal12 .

Also, please add back the lines in the table (like on the current website) between each row. 

Thanks

**Comment by ayushichoudhary-19** [comment]
I have successfully restyled the pages by making the necessary changes in `style.css` and respective view files as well.

This request solves the issue #82 

Screenshots of the changes:
image

image

image

Please review the styles. The EPS code is not rendering correctly in my browser, which has led to some inconsistencies in the display on my, as seen in the screenshot. However, this issue will not occur on your end.

**Review by MayankBansal12 — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
@ayushichoudhary-19 - Thanks for your contribution!

**Pull request merged**
