### PR TITLE
Added the search bar

### LINKED ISSUE #23: [FEAT] Seach-bar
A search bar on the top left corner of the website to search any name from the list/table.

### PR DESCRIPTION
**Pull request by bilalakhter**
Fixes #23 

- Added a search bar to the website.

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
- I need the button on the left, below YouTubers on this list
- Can you work on the styling a bit?

**Comment by bilalakhter** [comment]
sure

**Comment by KendallDoesCoding** [comment]
@bilalakhter - i want the styling of the search bar, something like this:
https://www.w3schools.com/howto/howto_css_searchbar.asp

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Thanks for your contribution @bilalakhter!!

**Pull request merged**
